---
alexa_site_verification: null
# Analytics
analytics:
  google:
    tracking_id: null
  provider: google-universal
atom_feed:
  path: null
# Site Author
author:
  avatar: profile.png
  bio: PhD Student in Applied and Computational Mathematics
  bitbucket: null
  codepen: null
  dribbble: null
  email: vo@acom.rwth-aachen.de
  employer: RWTH Aachen University
  facebook: null
  flickr: null
  foursquare: null
  github: tqnvo
  google_plus: null
  googlescholar: https://scholar.google.com/citations?user=f84qgOgAAAAJ&hl=de
  impactstory: https://www.mathematik.rwth-aachen.de/cms/mathematik/Die-Fachgruppe/Aktuell/Meldungen/~zlmdy/dr-rer-mat-night-18-01-2023-/?lidx=1
  instagram: null
  gitlab: "tqnvo"
  kaggle: tuanvqn
  keybase: null
  lastfm: null
  linkedin: tvqn
  location: Aachen, Germany
  name: Tuan Vo
  orcid: https://orcid.org/0000-0002-5472-1239
  pinterest: null
  pubmed: null
  researchgate: https://www.researchgate.net/profile/Tuan-Vo-4
  soundcloud: null
  stackoverflow: null
  steam: null
  tumblr: null
  twitter: tuan_vo
  uri: null
  vine: null
  weibo: null
  wikipedia: null
  xing: null
  youtube: null
  youtubelink: watch?v=a6RuXmKf4uM
baseurl: ""
bing_site_verification: null
breadcrumbs: false
# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  path: /categories/
  type: liquid
# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/
comments:
  discourse:
    server: null
  disqus:
    shortname: null
  facebook:
    appid: null
    colorscheme: null
    num_posts: null
  provider: null
# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      comments: true
      layout: single
      read_time: true
      related: true
      share: true
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
      layout: single
  - scope:
      path: ""
      type: teaching
    values:
      author_profile: true
      comments: true
      layout: single
      share: true
  - scope:
      path: ""
      type: publications
    values:
      author_profile: true
      comments: true
      layout: single
      share: true
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: true
      comment: true
      layout: single
      share: true
  # _talks
  # _portfolio
  # _publications
  # _teaching
  # _pages
  # _posts
  - scope:
      path: ""
      type: talks
    values:
      author_profile: true
      layout: talk
      share: true
description: personal description
encoding: utf-8
excerpt_separator: |+


exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
facebook:
  app_id: null
  publisher: null
  username: null
future: true
# SEO Related
google_site_verification: null
highlighter: rouge
# Reading Files
include:
  - .htaccess
  - _pages
  - files
incremental: false
keep_files:
  - .git
  - .svn
# Markdown Processing
kramdown:
  auto_ids: true
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  hard_wrap: false
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
# Site Settings
locale: en-GB
lsi: false
# Conversion
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
name: Tuan Vo
og_image: null
# Outputting
permalink: /:categories/:title/
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
read_more: disabled
repository: tqnvo/tqnvo.github.io
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  links: null
  name: null
  type: null
staticman:
  allowedFields: ["name", "email", "url", "message"]
  branch: gh-pages
  commitMessage: New comment.
  filename: comment-{@timestamp}
  format: yml
  generatedFields:
    date:
      options:
        format: timestamp-seconds
      type: date
  moderation: true
  path: _data/comments/{options.slug}
  requiredFields: ["name", "email", "message"]
  transforms:
    email: md5
tag_archive:
  path: /tags/
  type: liquid
talkmap_link: false
teaser: 500x300.png
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/Berlin
title: Tuan Vo
title_separator: "-"
# Social Sharing
twitter:
  username: null
url: https://tqnvo.github.io
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
words_per_minute: 160
yandex_site_verification: null# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/  # links:
# - label: "Youtube"
#   icon: "fas fa-fw fa-link"
#   url: "https://www.youtube.com/watch?v=a6RuXmKf4uM"#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# Welcome to Jekyll!
# `jekyll serve`. If you change this file, please restart the server process.
